# Generated by Django 5.0.6 on 2024-07-05 15:42

import parser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_remove_resume_data_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='resume_data',
            name='file',
            field=models.FileField(default=1, upload_to='resumes/', validators=[parser.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
