# Generated by Django 5.0.6 on 2024-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_resume_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume_data',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume_data',
            name='skills',
            field=models.ManyToManyField(to='parser.skill'),
        ),
    ]
